name = "Funhawg Podcast"
description = "Two friends who like to laugh, tell stories and thoughtfully consider how to navigate this incredible planet we were born on."
keywords = "funhawg, funhog, fun, podcast "
image = "jake.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = ""
base_url = "https://funhawg.github.io/jake"

[[sections]]
title = "Links"
description = "Find us on your favorite platform"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "SubStack"
url = "https://funhawg.substack.com/"
[[sections.items]]
title = "Itunes"
url = "https://podcasts.apple.com/us/podcast/funhawg-podcast/id1744215075"
[[sections.items]]
title = "Spotify"
url = "https://open.spotify.com/show/37hYKtLSrOZTa4jLWv19Wg?si=774424872723491e"
[[sections.items]]
title = "YouTube"
url = "https://www.youtube.com/channel/UCvnKwtGVcG7sY3ddfHDs1sg"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/funhawgpodcast/"
[[sections.items]]
title = "Facebook"
url = "https://www.youtube.com/channel/UCvnKwtGVcG7sY3ddfHDs1sg"
[[sections.items]]
title = "X - Twitter"
url = "https://www.youtube.com/channel/UCvnKwtGVcG7sY3ddfHDs1sg"

