name = "Funhawg Podcast"
description = "Two friends who like to laugh, tell stories and thoughtfully consider how to navigate this incredible planet we were born on."
keywords = "funhawg, funhog, fun, podcast"
image = "funhawg.webp"
theme = "light"
primary_color = "#FFA9FB"
text_align = "center"
gtag_id = "G-NSJFB4T7NT"
base_url = "https://funhawg.com"

[[sections]]
title = "Contact Us"
direction = "column"
item_style = "filled"
[[sections.items]]
title = "Contact Form"
url = "https://forms.gle/icjvKHMNoqKjeAwUA"

[[sections]]
title = "Links"
description = "Find us on your favorite platform"
direction = "column"
item_style = "filled"
[[sections.items]]
title = "Blog | SubStack"
url = "https://funhawg.substack.com/"
[[sections.items]]
title = "Itunes"
url = "https://podcasts.apple.com/us/podcast/funhawg-podcast/id1744215075"
[[sections.items]]
title = "Spotify"
url = "https://open.spotify.com/show/37hYKtLSrOZTa4jLWv19Wg?si=774424872723491e"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/funhawgpodcast/"
[[sections.items]]
title = "Facebook"
url = "https://www.facebook.com/profile.php?id=61559948257750"
[[sections.items]]
title = "X - Twitter"
url = "https://x.com/funhawgpodcast"
[[sections.items]]
title = "YouTube"
url = "https://www.youtube.com/channel/UCvnKwtGVcG7sY3ddfHDs1sg"